slam_toolbox:
  ros__parameters:
    # ============================================
    # STATE-OF-THE-ART SOLVER CONFIGURATION
    # Based on research in dynamic SLAM (Zhang et al. 2023, RoboCup@Home 2024)
    # ============================================
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY  # Best for large-scale SLAM
    ceres_preconditioner: SCHUR_JACOBI  # Superior for dynamic environments
    ceres_trust_strategy: LEVENBERG_MARQUARDT  # Robust optimization strategy
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss  # STATE-OF-ART: Robust to outliers from moving people
    ceres_huber_delta: 1.0  # Huber loss parameter for outlier rejection

    # Frame Configuration
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping

    # ============================================
    # FOLLOW-ME OPTIMIZED PARAMETERS
    # ============================================
    
    # Map Update Settings - Balance between accuracy and real-time performance
    map_update_interval: 0.2  # Increased interval for better performance
    resolution: 0.05
    min_laser_range: 0.3
    max_laser_range: 25.0
    minimum_time_interval: 0.10 
    transform_timeout: 0.2  # Increased tolerance for dynamic motion
    tf_buffer_duration: 30.0  # Longer buffer for better transform history
    stack_size_to_use: 20000000  # Reduced stack size for stability
    
    # ============================================
    # ADVANCED PROCESSING PARAMETERS
    # ============================================
    throttle_scans: 1  # Process every scan for smooth tracking
    transform_publish_period: 0.05  # Reduced frequency for better performance
    map_update_interval: 0.2  # Balance between map quality and CPU usage
    
    # ============================================
    # STATE-OF-THE-ART SCAN MATCHING
    # Adaptive parameters for dynamic person tracking
    # ============================================
    use_scan_matching: true
    use_scan_barycenter: true  # Better centroid estimation for moving scenarios
    minimum_travel_distance: 0.025  # Ultra-sensitive for smooth follow-me (SOTA)
    minimum_travel_heading: 0.025  # Ultra-sensitive rotation (SOTA)
    scan_buffer_size: 50  # Increased buffer for better temporal consistency and stability
    scan_buffer_maximum_scan_distance: 10.0  # Reduced for more local consistency
    link_match_minimum_response_fine: 0.2  # Increased for more reliable scan matches
    link_scan_maximum_distance: 2.5  # Reduced for tighter constraints
    
    # Advanced scan matching parameters (SOTA 2024)
    use_response_expansion: true  # Better handling of ambiguous matches
    max_laser_range: 25.0  # Full sensor range utilization
    
    # Loop Closure - Enabled with conservative parameters for stability
    loop_search_maximum_distance: 3.0  # Reduced for local loop closures
    do_loop_closing: false  # Enabled for map stability
    loop_match_minimum_chain_size: 15  # Increased for more reliable closures
    loop_match_maximum_variance_coarse: 3.0  # Reduced for stricter matching
    loop_match_minimum_response_coarse: 0.4  # Increased for better matches
    loop_match_minimum_response_fine: 0.6  # Increased for higher accuracy

    # ============================================
    # ADVANCED CORRELATION SEARCH SPACE (Optimized for real-time)
    # Reduced search space for better performance
    # ============================================
    correlation_search_space_dimension: 0.5  # Reduced search space for performance
    correlation_search_space_resolution: 0.01  # Coarser resolution for speed
    correlation_search_space_smear_deviation: 0.1  # Relaxed distribution
    
    # Multi-resolution correlation parameters
    coarse_search_angle_offset: 0.174  # ~10 degrees coarse search (reduced)
    coarse_angle_resolution: 0.052  # ~3 degree resolution (coarser)
    fine_search_angle_offset: 0.0087  # ~0.5 degree fine search (reduced) 

    # Loop Search Space (even though loop closure is off)
    loop_search_space_dimension: 3.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # ============================================
    # STATE-OF-THE-ART VARIANCE & PENALTY TUNING
    # Optimized for smooth dynamic tracking
    # ============================================
    distance_variance_penalty: 0.25  # Very low for fluid motion (SOTA)
    angle_variance_penalty: 0.7  # Reduced for smoother rotation (SOTA)
    
    # Advanced penalty parameters for person-following
    minimum_angle_penalty: 0.85  # Allow more angular flexibility
    minimum_distance_penalty: 0.4  # Allow more translational flexibility
    
    # ============================================
    # ROBUSTNESS PARAMETERS (SOTA 2024)
    # ============================================
    # Outlier rejection for moving people - TUNED FOR PERSON FOLLOWING
    outlier_rejection_enabled: true  # Filter dynamic obstacles from map
    outlier_angle_threshold: 0.1  # Reduced from 0.5 - detect smaller angular movements (SOTA)
    outlier_distance_threshold: 0.05  # Reduced from 0.3 - detect smaller translations (SOTA)
    
    # Advanced parameters to require more points for static objects
    min_pass_through: 4 # Increased from default 2 - require more beams to consider occupied
    occupancy_threshold: 0.3  # Increased from default 0.1 - require higher ratio of hits to passes
    
    # Adaptive parameters
    enable_interactive_mode: false  # Disable GUI for better performance
    async_publish: true  # Non-blocking map publishing
    
    # Performance optimization
    number_of_threads: 4  # Multi-threading for modern CPUs
    
    # Advanced range parameters
    max_laser_range: 25.0
    minimum_laser_range: 0.3