slam_toolbox:
  ros__parameters:
    # ============================================
    # STATE-OF-THE-ART SOLVER CONFIGURATION
    # Based on research in dynamic SLAM (Zhang et al. 2023, RoboCup@Home 2024)
    # ============================================
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY  # Best for large-scale SLAM
    ceres_preconditioner: SCHUR_JACOBI  # Superior for dynamic environments
    ceres_trust_strategy: LEVENBERG_MARQUARDT  # Robust optimization strategy
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss  # STATE-OF-ART: Robust to outliers from moving people
    ceres_huber_delta: 1.0  # Huber loss parameter for outlier rejection

    # Frame Configuration
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping

    # ============================================
    # FOLLOW-ME OPTIMIZED PARAMETERS
    # ============================================
    
    # Map Update Settings - Balance between accuracy and real-time performance
    map_update_interval: 0.15  # Optimized for follow-me CPU usage
    resolution: 0.05
    min_laser_range: 0.3
    max_laser_range: 25.0
    minimum_time_interval: 0.10 
    transform_timeout: 0.2  # Increased tolerance for dynamic motion
    tf_buffer_duration: 30.0  # Longer buffer for better transform history
    stack_size_to_use: 40000000
    
    # ============================================
    # ADVANCED PROCESSING PARAMETERS
    # ============================================
    throttle_scans: 1  # Process every scan for smooth tracking
    transform_publish_period: 0.02  # 50Hz transform updates for real-time responsiveness
    map_update_interval: 0.15  # Balance between map quality and CPU usage
    
    # ============================================
    # STATE-OF-THE-ART SCAN MATCHING
    # Adaptive parameters for dynamic person tracking
    # ============================================
    use_scan_matching: true
    use_scan_barycenter: true  # Better centroid estimation for moving scenarios
    minimum_travel_distance: 0.02  # Ultra-sensitive for smooth follow-me (SOTA)
    minimum_travel_heading: 0.025  # Ultra-sensitive rotation (SOTA)
    scan_buffer_size: 35  # Larger buffer for temporal consistency (SOTA)
    scan_buffer_maximum_scan_distance: 12.0  # Extended range for person tracking (SOTA)
    link_match_minimum_response_fine: 0.15  # Lower for better sensitivity in dynamic env
    link_scan_maximum_distance: 3.0  # Wider search for moving obstacles (SOTA)
    
    # Advanced scan matching parameters (SOTA 2024)
    use_response_expansion: true  # Better handling of ambiguous matches
    max_laser_range: 25.0  # Full sensor range utilization
    
    # Loop Closure - Disabled for follow-me to avoid sudden corrections
    loop_search_maximum_distance: 5.0
    do_loop_closing: false  # Keep disabled - critical for smooth follow-me
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 5.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.5

    # ============================================
    # ADVANCED CORRELATION SEARCH SPACE (SOTA)
    # Multi-resolution search for robust matching
    # ============================================
    correlation_search_space_dimension: 0.7  # Wider search for dynamic tracking (SOTA)
    correlation_search_space_resolution: 0.008  # Finer resolution for precision (SOTA)
    correlation_search_space_smear_deviation: 0.08  # Tighter distribution (SOTA)
    
    # Multi-resolution correlation parameters
    coarse_search_angle_offset: 0.349  # ~20 degrees coarse search
    coarse_angle_resolution: 0.0349  # ~2 degree resolution
    fine_search_angle_offset: 0.00349  # ~0.2 degree fine search 

    # Loop Search Space (even though loop closure is off)
    loop_search_space_dimension: 3.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # ============================================
    # STATE-OF-THE-ART VARIANCE & PENALTY TUNING
    # Optimized for smooth dynamic tracking
    # ============================================
    distance_variance_penalty: 0.25  # Very low for fluid motion (SOTA)
    angle_variance_penalty: 0.7  # Reduced for smoother rotation (SOTA)
    
    # Advanced penalty parameters for person-following
    minimum_angle_penalty: 0.85  # Allow more angular flexibility
    minimum_distance_penalty: 0.4  # Allow more translational flexibility
    
    # ============================================
    # ROBUSTNESS PARAMETERS (SOTA 2024)
    # ============================================
    # Outlier rejection for moving people
    outlier_rejection_enabled: true  # Filter dynamic obstacles from map
    outlier_angle_threshold: 0.5  # Radians threshold for outlier detection
    outlier_distance_threshold: 0.3  # Meters threshold for outlier detection
    
    # Adaptive parameters
    enable_interactive_mode: false  # Disable GUI for better performance
    async_publish: true  # Non-blocking map publishing
    
    # Performance optimization
    number_of_threads: 4  # Multi-threading for modern CPUs
    
    # Advanced range parameters
    max_laser_range: 25.0
    minimum_laser_range: 0.3