slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping

    map_update_interval: 0.1  # Update the map more frequently
    resolution: 0.05
    min_laser_range: 0.3
    max_laser_range: 25.0
    minimum_time_interval: 0.10 
    transform_timeout: 0.1  # Slightly increased to allow more time for TFs
    tf_buffer_duration: 15.0
    stack_size_to_use: 40000000

    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.05  # More sensitive to smaller movements
    minimum_travel_heading: 0.05  # More sensitive to small angle changes
    scan_buffer_size: 20  # Increased buffer for scan matching
    scan_buffer_maximum_scan_distance: 5.0  # Focus on nearby scans for better matching
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 5.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 5.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.5

    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1 

    loop_search_space_dimension: 3.0  # Reduced to focus on tighter loops
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0    
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349